import os
import lamini
from dotenv import load_dotenv

load_dotenv()

lamini.api_key = os.getenv("LAMINI_API_KEY")

llm = lamini.Lamini(model_name="meta-llama/Meta-Llama-3-8B-Instruct")


def get_data():
    return [
        {"question": "What is the expected contribution of N5 to TSMC's wafer revenue in 2021?",
            "answer": "The expected contribution of N5 to TSMC's wafer revenue in 2021 is around 20%."},
        {"question": "What percentage of TSMC's wafer revenue in 2021 is attributed to the N5 technology node?",
            "answer": "The expected contribution of N5 to TSMC's wafer revenue in 2021 is around 20%."},
        {"question": "What is the estimated proportion of N5-based wafer sales to TSMC's total wafer revenue in 2021?",
            "answer": "The expected contribution of N5 to TSMC's wafer revenue in 2021 is around 20%."},
        {"question": "What is the expected share of N5 technology in TSMC's wafer revenue for the year 2021?",
            "answer": "The expected contribution of N5 to TSMC's wafer revenue in 2021 is around 20%."},
        {"question": "What is the approximate percentage of TSMC's wafer revenue in 2021 that can be attributed to the N5 node?",
            "answer": "The expected contribution of N5 to TSMC's wafer revenue in 2021 is around 20%."},
        {"question": "What is TSMC expected full-year growth in U.S. dollar terms for 2022?",
            "answer": "TSMC's expected full-year growth in U.S. dollar terms for 2022 is mid-30%."},
        {"question": "What is TSMC's projected growth rate in U.S. dollar terms for the full year 2022?",
            "answer": "TSMC's expected full-year growth in U.S. dollar terms for 2022 is mid-30%."},
        {"question": "What is the expected percentage increase in TSMC's revenue in U.S. dollar terms for the year 2022?",
            "answer": "TSMC's expected full-year growth in U.S. dollar terms for 2022 is mid-30%."},
        {"question": "What is the forecasted growth rate of TSMC's revenue in U.S. dollar terms for the full year 2022?",
            "answer": "TSMC's expected full-year growth in U.S. dollar terms for 2022 is mid-30%."},
        {"question": "What is the anticipated percentage change in TSMC's revenue in U.S. dollar terms for the year 2022?",
            "answer": "TSMC's expected full-year growth in U.S. dollar terms for 2022 is mid-30%."},
        {"question": "What is the expected production schedule for TSMC N4X?",
            "answer": "The expected production schedule for N4X is in the first half of 2023."},
        {"question": "When is TSMC planning to start mass-producing the N4X technology node?",
            "answer": "The expected production schedule for N4X is in the first half of 2023."},
        {"question": "What is the expected timeline for the commercial availability of N4X wafers from TSMC?",
            "answer": "The expected production schedule for N4X is in the first half of 2023."},
        {"question": "When is TSMC expected to begin volume production of N4X-based wafers?",
            "answer": "The expected production schedule for N4X is in the first half of 2023."},
        {"question": "What is the anticipated production window for N4X technology from TSMC?",
            "answer": "The expected production schedule for N4X is in the first half of 2023."},
        {"question": "What is TSMC forecast for foundry industry growth in 2021 in U.S. dollar terms?",
            "answer": "TSMC's forecast for the foundry industry growth in 2021 in U.S. dollar terms is around 16%."},
        {"question": "What is TSMC's predicted growth rate for the foundry industry in U.S. dollar terms for the year 2021?",
            "answer": "TSMC's forecast for the foundry industry growth in 2021 in U.S. dollar terms is around 16%."},
        {"question": "What is the expected percentage increase in foundry industry revenue in U.S. dollar terms for 2021, according to TSMC's forecast?",
            "answer": "TSMC's forecast for the foundry industry growth in 2021 in U.S. dollar terms is around 16%."},
        {"question": "What is TSMC's forecasted growth rate for the global foundry market in U.S. dollar terms for the year 2021?",
            "answer": "TSMC's forecast for the foundry industry growth in 2021 in U.S. dollar terms is around 16%."},
        {"question": "What is the anticipated growth rate of the foundry industry in U.S. dollar terms for 2021, as predicted by TSMC?",
            "answer": "TSMC's forecast for the foundry industry growth in 2021 in U.S. dollar terms is around 16%."},
        {"question": "What is the breakdown of TSMC 2021 capital budget allocation by technology?",
            "answer": "The breakdown of TSMC's 2021 capital budget allocation by technology is as follows: 80% will be allocated for advanced process technologies, including 3-nanometer, 5-nanometer, and 7-nanometer.\n* 10% will be spent for advanced packaging and mask making.\n* 10% will be spent for specialty technologies."},
        {"question": "What percentage of TSMC's 2021 capital budget will be allocated to advanced process technologies, including 3-nanometer, 5-nanometer, and 7-nanometer?",
            "answer": "The breakdown of TSMC's 2021 capital budget allocation by technology is as follows: 80% will be allocated for advanced process technologies, including 3-nanometer, 5-nanometer, and 7-nanometer.\n* 10% will be spent for advanced packaging and mask making.\n* 10% will be spent for specialty technologies."},
        {"question": "How much of TSMC's 2021 capital budget will be dedicated to advanced packaging and mask making?",
            "answer": "The breakdown of TSMC's 2021 capital budget allocation by technology is as follows: 80% will be allocated for advanced process technologies, including 3-nanometer, 5-nanometer, and 7-nanometer.\n* 10% will be spent for advanced packaging and mask making.\n* 10% will be spent for specialty technologies."},
        {"question": "What proportion of TSMC's 2021 capital budget will be spent on specialty technologies?",
            "answer": "The breakdown of TSMC's 2021 capital budget allocation by technology is as follows: 80% will be allocated for advanced process technologies, including 3-nanometer, 5-nanometer, and 7-nanometer.\n* 10% will be spent for advanced packaging and mask making.\n* 10% will be spent for specialty technologies."},
        {"question": "What percentage of TSMC's 2021 capital budget will be allocated to 3-nanometer, 5-nanometer, and 7-nanometer process technologies combined?",
            "answer": "The breakdown of TSMC's 2021 capital budget allocation by technology is as follows: 80% will be allocated for advanced process technologies, including 3-nanometer, 5-nanometer, and 7-nanometer.\n* 10% will be spent for advanced packaging and mask making.\n* 10% will be spent for specialty technologies."},
        {"question": "What is the expected revenue growth rate for TSMC from 2020 to 2025 in U.S. dollar terms?",
            "answer": "The expected revenue growth rate for TSMC from 2020 to 2025 in U.S. dollar terms is between 10% to 15%."},
        {"question": "What is the projected annual growth rate of TSMC's revenue from 2020 to 2025, expressed as a percentage?",
            "answer": "The expected revenue growth rate for TSMC from 2020 to 2025 in U.S. dollar terms is between 10% to 15%."},
        {"question": "What is the estimated compound annual growth rate (CAGR) of TSMC's revenue from 2020 to 2025 in U.S. dollar terms?",
         "answer": "The expected revenue growth rate for TSMC from 2020 to 2025 in U.S. dollar terms is between 10% to 15%."},
        {"question": "What is the range of expected revenue growth for TSMC from 2020 to 2025, in terms of percentage increase per annum?",
            "answer": "The expected revenue growth rate for TSMC from 2020 to 2025 in U.S. dollar terms is between 10% to 15%."},
        {"question": "What is the forecasted annual revenue growth rate for TSMC from 2020 to 2025, expressed as a percentage, based on industry trends and analyst estimates?",
            "answer": "The expected revenue growth rate for TSMC from 2020 to 2025 in U.S. dollar terms is between 10% to 15%."},
        {"question": "What was TSMC revenue in US dollar terms in 2019?",
            "answer": "TSMC's revenue in US dollar terms in 2019 was USD 34.6 billion."},
        {"question": "What was TSMC revenue in US dollar terms for the year 2019?",
            "answer": "TSMC's revenue in US dollar terms in 2019 was USD 34.6 billion."},
        {"question": "What was TSMC total revenue in US dollars for the calendar year 2019?",
            "answer": "TSMC's revenue in US dollar terms in 2019 was USD 34.6 billion."},
        {"question": "What was TSMC annual revenue in US dollars for the year ending December 31, 2019?",
            "answer": "TSMC's revenue in US dollar terms in 2019 was USD 34.6 billion."},
        {"question": "What was TSMC revenue in US dollar terms for the fiscal year 2019?",
            "answer": "TSMC's revenue in US dollar terms in 2019 was USD 34.6 billion."},
        {"question": "What is the expected revenue growth for TSMC in 2022-Q2 in U.S. dollar terms?",
            "answer": "The expected revenue growth for TSMC in 2022-Q2 in U.S. dollar terms is 35%."},
        {"question": "What is the projected annual growth rate of Taiwan Semiconductor Manufacturing Company's (TSMC) revenue from 2020 to 2025, assuming a moderate growth scenario?",
         "answer": "The expected revenue growth for TSMC in 2022-Q2 in U.S. dollar terms is 35%."},
        {"question": "What is the estimated compound annual growth rate (CAGR) of TSMC's revenue from 2020 to 2025, considering the company's historical growth trends and industry developments?",
         "answer": "The expected revenue growth for TSMC in 2022-Q2 in U.S. dollar terms is 35%."},
        {"question": "What is the range of possible revenue growth rates for TSMC from 2020 to 2025, based on analyst forecasts and industry reports?",
            "answer": "The expected revenue growth for TSMC in 2022-Q2 in U.S. dollar terms is 35%."},
        {"question": "What is the expected average annual growth rate of TSMC's revenue from 2020 to 2025, considering the company's strategic initiatives, market trends, and competitive landscape?",
            "answer": "The expected revenue growth for TSMC in 2022-Q2 in U.S. dollar terms is 35%."},
        {"question": "What is the expected power improvement at the same speed for N2 compared to TSMC N3e?",
            "answer": "The expected power improvement at the same speed for N2 compared to N3e is 20% to 30%."},
        {"question": "What is the estimated percentage increase in power efficiency that can be achieved by using N2 technology compared to N3e, assuming the same operating speed?",
            "answer": "The expected power improvement at the same speed for N2 compared to N3e is 20% to 30%."},
        {"question": "What is the expected power reduction percentage for N2 technology compared to N3e, assuming the same clock speed?",
            "answer": "The expected power improvement at the same speed for N2 compared to N3e is 20% to 30%."},
        {"question": "What is the power improvement range that can be expected when transitioning from N3e to N2 technology, measured as a percentage of the original power consumption at the same clock speed?",
            "answer": "The expected power improvement at the same speed for N2 compared to N3e is 20% to 30%."},
        {"question": "What is the estimated power savings percentage that can be achieved by using N2 technology compared to N3e, assuming the same operating frequency?",
            "answer": "The expected power improvement at the same speed for N2 compared to N3e is 20% to 30%."},
        {"question": "What is TSMC expected foundry industry growth for the full year of 2022?",
            "answer": "TSMC's expected foundry industry growth for the full year of 2022 is forecast to be close to 20%."},
        {"question": "What is TSMC annual growth rate for full year 2022 based on current market trends and forecasts?",
            "answer": "TSMC's expected foundry industry growth for the full year of 2022 is forecast to be close to 20%."},
        {"question": "What is the expected annual growth rate for the global foundry market, with TSMC being a major player, for the year 2022, according to industry analysts and research firms?",
            "answer": "TSMC's expected foundry industry growth for the full year of 2022 is forecast to be close to 20%."},
        {"question": "What is the forecasted growth rate for thesemiconductor foundry industry, with TSMC being a key player, for the full year 2022, considering the current market conditions and demand trends?",
            "answer": "TSMC's expected foundry industry growth for the full year of 2022 is forecast to be close to 20%."},
        {"question": "What is the estimated growth rate for the foundry industry, driven by TSMC and other major players, for the year 2022, based on industry reports and market research?",
            "answer": "TSMC's expected foundry industry growth for the full year of 2022 is forecast to be close to 20%."},
    ]


data = get_data()

llm.tune(data_or_dataset_id=data,
         finetune_args={'learning_rate': 1.0e-4}
         )
